// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class IWICBitmapEncoderInfo: IWICBitmapCodecInfo
    {
        static Guid s_uuid = new Guid("94c9b4ee-a09f-4f92-8a1e-4a9bce7e76fb");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int CreateInstance(
            out IWICBitmapEncoder ppIBitmapEncoder
        ){
            var fp = GetFunctionPointer(23);
            if(m_CreateInstanceFunc==null) m_CreateInstanceFunc = (CreateInstanceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(CreateInstanceFunc));
            ppIBitmapEncoder = new IWICBitmapEncoder();
            return m_CreateInstanceFunc(m_ptr, out ppIBitmapEncoder.PtrForNew);
        }
        delegate int CreateInstanceFunc(IntPtr self, out IntPtr ppIBitmapEncoder);
        CreateInstanceFunc m_CreateInstanceFunc;

    }
}
