// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum WICComponentSigning // 1
    {
        WICComponentSigned = 0x1,
        WICComponentUnsigned = 0x2,
        WICComponentSafe = 0x4,
        WICComponentDisabled = unchecked((int)0x80000000),
        WICCOMPONENTSIGNING_FORCE_DWORD = 0x7fffffff,
    }
}
