// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum WICGifCommentExtensionProperties // 1
    {
        WICGifCommentExtensionText = 0x1,
        _FORCE_DWORD = 0x7fffffff,
    }
}
