// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum WICRawRotationCapabilities // 1
    {
        WICRawRotationCapabilityNotSupported = 0x0,
        WICRawRotationCapabilityGetSupported = 0x1,
        WICRawRotationCapabilityNinetyDegreesSupported = 0x2,
        WICRawRotationCapabilityFullySupported = 0x3,
        WICRAWROTATIONCAPABILITIES_FORCE_DWORD = 0x7fffffff,
    }
}
