// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum tagSYSKIND // 1
    {
        _WIN16 = 0x0,
        _WIN32 = 0x1,
        _MAC = 0x2,
        _WIN64 = 0x3,
    }
}
