// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID3D10EffectDepthStencilVariable: ID3D10EffectVariable
    {
        static Guid s_uuid = new Guid("af482368-330a-46a5-9a5c-01c71af24c8d");
        public static new ref Guid IID => ref s_uuid;
                
        public virtual int GetDepthStencilState(
            uint Index,
            out ID3D10DepthStencilState ppDepthStencilState
        ){
            var fp = GetFunctionPointer(25);
            if(m_GetDepthStencilStateFunc==null) m_GetDepthStencilStateFunc = (GetDepthStencilStateFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDepthStencilStateFunc));
            ppDepthStencilState = new ID3D10DepthStencilState();
            return m_GetDepthStencilStateFunc(m_ptr, Index, out ppDepthStencilState.PtrForNew);
        }
        delegate int GetDepthStencilStateFunc(IntPtr self, uint Index, out IntPtr ppDepthStencilState);
        GetDepthStencilStateFunc m_GetDepthStencilStateFunc;

        public virtual int GetBackingStore(
            uint Index,
            out D3D10_DEPTH_STENCIL_DESC pDepthStencilDesc
        ){
            var fp = GetFunctionPointer(26);
            if(m_GetBackingStoreFunc==null) m_GetBackingStoreFunc = (GetBackingStoreFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetBackingStoreFunc));
            
            return m_GetBackingStoreFunc(m_ptr, Index, out pDepthStencilDesc);
        }
        delegate int GetBackingStoreFunc(IntPtr self, uint Index, out D3D10_DEPTH_STENCIL_DESC pDepthStencilDesc);
        GetBackingStoreFunc m_GetBackingStoreFunc;

    }
}
