// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_RAYTRACING_GEOMETRY_TYPE // 1
    {
        _TRIANGLES = 0x0,
        _PROCEDURAL_PRIMITIVE_AABBS = 0x1,
    }
}
