// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_INDEX_BUFFER_STRIP_CUT_VALUE // 1
    {
        _DISABLED = 0x0,
        _0xFFFF = 0x1,
        _0xFFFFFFFF = 0x2,
    }
}
