// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_PREDICATION_OP // 1
    {
        _EQUAL_ZERO = 0x0,
        _NOT_EQUAL_ZERO = 0x1,
    }
}
