// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_FORMAT_SUPPORT2 // 1
    {
        _NONE = 0x0,
        _UAV_ATOMIC_ADD = 0x1,
        _UAV_ATOMIC_BITWISE_OPS = 0x2,
        _UAV_ATOMIC_COMPARE_STORE_OR_COMPARE_EXCHANGE = 0x4,
        _UAV_ATOMIC_EXCHANGE = 0x8,
        _UAV_ATOMIC_SIGNED_MIN_OR_MAX = 0x10,
        _UAV_ATOMIC_UNSIGNED_MIN_OR_MAX = 0x20,
        _UAV_TYPED_LOAD = 0x40,
        _UAV_TYPED_STORE = 0x80,
        _OUTPUT_MERGER_LOGIC_OP = 0x100,
        _TILED = 0x200,
        _MULTIPLANE_OVERLAY = 0x4000,
    }
}
