// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_DSV_DIMENSION // 1
    {
        _UNKNOWN = 0x0,
        _TEXTURE1D = 0x1,
        _TEXTURE1DARRAY = 0x2,
        _TEXTURE2D = 0x3,
        _TEXTURE2DARRAY = 0x4,
        _TEXTURE2DMS = 0x5,
        _TEXTURE2DMSARRAY = 0x6,
    }
}
