// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_VIEW_INSTANCING_FLAGS // 1
    {
        _NONE = 0x0,
        _ENABLE_VIEW_INSTANCE_MASKING = 0x1,
    }
}
