// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_META_COMMAND_PARAMETER_STAGE // 1
    {
        _CREATION = 0x0,
        _INITIALIZATION = 0x1,
        _EXECUTION = 0x2,
    }
}
