// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_BLEND // 1
    {
        _ZERO = 0x1,
        _ONE = 0x2,
        _SRC_COLOR = 0x3,
        _INV_SRC_COLOR = 0x4,
        _SRC_ALPHA = 0x5,
        _INV_SRC_ALPHA = 0x6,
        _DEST_ALPHA = 0x7,
        _INV_DEST_ALPHA = 0x8,
        _DEST_COLOR = 0x9,
        _INV_DEST_COLOR = 0xa,
        _SRC_ALPHA_SAT = 0xb,
        _BLEND_FACTOR = 0xe,
        _INV_BLEND_FACTOR = 0xf,
        _SRC1_COLOR = 0x10,
        _INV_SRC1_COLOR = 0x11,
        _SRC1_ALPHA = 0x12,
        _INV_SRC1_ALPHA = 0x13,
    }
}
