// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_SHADER_MIN_PRECISION_SUPPORT // 1
    {
        _NONE = 0x0,
        _10_BIT = 0x1,
        _16_BIT = 0x2,
    }
}
