// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_RENDER_PASS_FLAGS // 1
    {
        _NONE = 0x0,
        _ALLOW_UAV_WRITES = 0x1,
        _SUSPENDING_PASS = 0x2,
        _RESUMING_PASS = 0x4,
    }
}
