// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D12_STATE_OBJECT_TYPE // 1
    {
        _COLLECTION = 0x0,
        _RAYTRACING_PIPELINE = 0x3,
    }
}
