// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID3D12GraphicsCommandList3: ID3D12GraphicsCommandList2
    {
        static Guid s_uuid = new Guid("6fda83a7-b84c-4e38-9ac8-c7bd22016b3d");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual void SetProtectedResourceSession(
            ID3D12ProtectedResourceSession pProtectedResourceSession
        ){
            var fp = GetFunctionPointer(67);
            if(m_SetProtectedResourceSessionFunc==null) m_SetProtectedResourceSessionFunc = (SetProtectedResourceSessionFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetProtectedResourceSessionFunc));
            
            m_SetProtectedResourceSessionFunc(m_ptr, pProtectedResourceSession!=null ? pProtectedResourceSession.Ptr : IntPtr.Zero);
        }
        delegate void SetProtectedResourceSessionFunc(IntPtr self, IntPtr pProtectedResourceSession);
        SetProtectedResourceSessionFunc m_SetProtectedResourceSessionFunc;

    }
}
