// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID3D12Pageable: ID3D12DeviceChild
    {
        static Guid s_uuid = new Guid("63ee58fb-1268-4835-86da-f008ce62f0d6");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
    }
}
