// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DWRITE_WORD_WRAPPING // 2
    {
        _WRAP = 0x0,
        _NO_WRAP = 0x1,
        _EMERGENCY_BREAK = 0x2,
        _WHOLE_WORD = 0x3,
        _CHARACTER = 0x4,
    }
}
