// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DWRITE_FLOW_DIRECTION // 4
    {
        _TOP_TO_BOTTOM = 0x0,
        _BOTTOM_TO_TOP = 0x1,
        _LEFT_TO_RIGHT = 0x2,
        _RIGHT_TO_LEFT = 0x3,
    }
}
