// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DWRITE_RENDERING_MODE // 4
    {
        _DEFAULT = 0x0,
        _ALIASED = 0x1,
        _GDI_CLASSIC = 0x2,
        _GDI_NATURAL = 0x3,
        _NATURAL = 0x4,
        _NATURAL_SYMMETRIC = 0x5,
        _OUTLINE = 0x6,
        _CLEARTYPE_GDI_CLASSIC = 0x2,
        _CLEARTYPE_GDI_NATURAL = 0x3,
        _CLEARTYPE_NATURAL = 0x4,
        _CLEARTYPE_NATURAL_SYMMETRIC = 0x5,
    }
}
