// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DWRITE_FONT_STRETCH // 7
    {
        _UNDEFINED = 0x0,
        _ULTRA_CONDENSED = 0x1,
        _EXTRA_CONDENSED = 0x2,
        _CONDENSED = 0x3,
        _SEMI_CONDENSED = 0x4,
        _NORMAL = 0x5,
        _MEDIUM = 0x5,
        _SEMI_EXPANDED = 0x6,
        _EXPANDED = 0x7,
        _EXTRA_EXPANDED = 0x8,
        _ULTRA_EXPANDED = 0x9,
    }
}
