// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class IDWriteRenderingParams: IUnknown
    {
        static Guid s_uuid = new Guid("2f0da53a-2add-47cd-82ee-d9ec34688e75");
        public static new ref Guid IID => ref s_uuid;
                
        public virtual float GetGamma(
        ){
            var fp = GetFunctionPointer(3);
            if(m_GetGammaFunc==null) m_GetGammaFunc = (GetGammaFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetGammaFunc));
            
            return m_GetGammaFunc(m_ptr);
        }
        delegate float GetGammaFunc(IntPtr self);
        GetGammaFunc m_GetGammaFunc;

        public virtual float GetEnhancedContrast(
        ){
            var fp = GetFunctionPointer(4);
            if(m_GetEnhancedContrastFunc==null) m_GetEnhancedContrastFunc = (GetEnhancedContrastFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetEnhancedContrastFunc));
            
            return m_GetEnhancedContrastFunc(m_ptr);
        }
        delegate float GetEnhancedContrastFunc(IntPtr self);
        GetEnhancedContrastFunc m_GetEnhancedContrastFunc;

        public virtual float GetClearTypeLevel(
        ){
            var fp = GetFunctionPointer(5);
            if(m_GetClearTypeLevelFunc==null) m_GetClearTypeLevelFunc = (GetClearTypeLevelFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetClearTypeLevelFunc));
            
            return m_GetClearTypeLevelFunc(m_ptr);
        }
        delegate float GetClearTypeLevelFunc(IntPtr self);
        GetClearTypeLevelFunc m_GetClearTypeLevelFunc;

        public virtual DWRITE_PIXEL_GEOMETRY GetPixelGeometry(
        ){
            var fp = GetFunctionPointer(6);
            if(m_GetPixelGeometryFunc==null) m_GetPixelGeometryFunc = (GetPixelGeometryFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetPixelGeometryFunc));
            
            return m_GetPixelGeometryFunc(m_ptr);
        }
        delegate DWRITE_PIXEL_GEOMETRY GetPixelGeometryFunc(IntPtr self);
        GetPixelGeometryFunc m_GetPixelGeometryFunc;

        public virtual DWRITE_RENDERING_MODE GetRenderingMode(
        ){
            var fp = GetFunctionPointer(7);
            if(m_GetRenderingModeFunc==null) m_GetRenderingModeFunc = (GetRenderingModeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetRenderingModeFunc));
            
            return m_GetRenderingModeFunc(m_ptr);
        }
        delegate DWRITE_RENDERING_MODE GetRenderingModeFunc(IntPtr self);
        GetRenderingModeFunc m_GetRenderingModeFunc;

    }
}
