// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_EXTEND_MODE // 1
    {
        _CLAMP = 0x0,
        _WRAP = 0x1,
        _MIRROR = 0x2,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
