// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_WINDOW_STATE // 1
    {
        _NONE = 0x0,
        _OCCLUDED = 0x1,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
