// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_FILL_MODE // 1
    {
        _ALTERNATE = 0x0,
        _WINDING = 0x1,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
