// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_ARC_SIZE // 1
    {
        _SMALL = 0x0,
        _LARGE = 0x1,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
