// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID2D1LinearGradientBrush: ID2D1Brush
    {
        static Guid s_uuid = new Guid("2cd906ab-12e2-11dc-9fed-001143a055f9");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual void SetStartPoint(
            System.Numerics.Vector2 startPoint
        ){
            var fp = GetFunctionPointer(8);
            if(m_SetStartPointFunc==null) m_SetStartPointFunc = (SetStartPointFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetStartPointFunc));
            
            m_SetStartPointFunc(m_ptr, startPoint);
        }
        delegate void SetStartPointFunc(IntPtr self, System.Numerics.Vector2 startPoint);
        SetStartPointFunc m_SetStartPointFunc;

        public virtual void SetEndPoint(
            System.Numerics.Vector2 endPoint
        ){
            var fp = GetFunctionPointer(9);
            if(m_SetEndPointFunc==null) m_SetEndPointFunc = (SetEndPointFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetEndPointFunc));
            
            m_SetEndPointFunc(m_ptr, endPoint);
        }
        delegate void SetEndPointFunc(IntPtr self, System.Numerics.Vector2 endPoint);
        SetEndPointFunc m_SetEndPointFunc;

        public virtual System.Numerics.Vector2 GetStartPoint(
        ){
            var fp = GetFunctionPointer(10);
            if(m_GetStartPointFunc==null) m_GetStartPointFunc = (GetStartPointFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetStartPointFunc));
            
            return m_GetStartPointFunc(m_ptr);
        }
        delegate System.Numerics.Vector2 GetStartPointFunc(IntPtr self);
        GetStartPointFunc m_GetStartPointFunc;

        public virtual System.Numerics.Vector2 GetEndPoint(
        ){
            var fp = GetFunctionPointer(11);
            if(m_GetEndPointFunc==null) m_GetEndPointFunc = (GetEndPointFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetEndPointFunc));
            
            return m_GetEndPointFunc(m_ptr);
        }
        delegate System.Numerics.Vector2 GetEndPointFunc(IntPtr self);
        GetEndPointFunc m_GetEndPointFunc;

        public virtual void GetGradientStopCollection(
            out ID2D1GradientStopCollection gradientStopCollection
        ){
            var fp = GetFunctionPointer(12);
            if(m_GetGradientStopCollectionFunc==null) m_GetGradientStopCollectionFunc = (GetGradientStopCollectionFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetGradientStopCollectionFunc));
            gradientStopCollection = new ID2D1GradientStopCollection();
            m_GetGradientStopCollectionFunc(m_ptr, out gradientStopCollection.PtrForNew);
        }
        delegate void GetGradientStopCollectionFunc(IntPtr self, out IntPtr gradientStopCollection);
        GetGradientStopCollectionFunc m_GetGradientStopCollectionFunc;

    }
}
