// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class IPrintDocumentPackageTarget: IUnknown
    {
        static Guid s_uuid = new Guid("1b8efec4-3019-4c27-964e-367202156906");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int GetPackageTargetTypes(
            out uint targetCount,
            out IntPtr targetTypes
        ){
            var fp = GetFunctionPointer(3);
            if(m_GetPackageTargetTypesFunc==null) m_GetPackageTargetTypesFunc = (GetPackageTargetTypesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetPackageTargetTypesFunc));
            
            return m_GetPackageTargetTypesFunc(m_ptr, out targetCount, out targetTypes);
        }
        delegate int GetPackageTargetTypesFunc(IntPtr self, out uint targetCount, out IntPtr targetTypes);
        GetPackageTargetTypesFunc m_GetPackageTargetTypesFunc;

        public virtual int GetPackageTarget(
            ref Guid guidTargetType,
            ref Guid riid,
            out IntPtr ppvTarget
        ){
            var fp = GetFunctionPointer(4);
            if(m_GetPackageTargetFunc==null) m_GetPackageTargetFunc = (GetPackageTargetFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetPackageTargetFunc));
            
            return m_GetPackageTargetFunc(m_ptr, ref guidTargetType, ref riid, out ppvTarget);
        }
        delegate int GetPackageTargetFunc(IntPtr self, ref Guid guidTargetType, ref Guid riid, out IntPtr ppvTarget);
        GetPackageTargetFunc m_GetPackageTargetFunc;

        public virtual int Cancel(
        ){
            var fp = GetFunctionPointer(5);
            if(m_CancelFunc==null) m_CancelFunc = (CancelFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(CancelFunc));
            
            return m_CancelFunc(m_ptr);
        }
        delegate int CancelFunc(IntPtr self);
        CancelFunc m_CancelFunc;

    }
}
