// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_VIDEO_DECODER_BUFFER_TYPE // 1
    {
        _PICTURE_PARAMETERS = 0x0,
        _MACROBLOCK_CONTROL = 0x1,
        _RESIDUAL_DIFFERENCE = 0x2,
        _DEBLOCKING_CONTROL = 0x3,
        _INVERSE_QUANTIZATION_MATRIX = 0x4,
        _SLICE_CONTROL = 0x5,
        _BITSTREAM = 0x6,
        _MOTION_VECTOR = 0x7,
        _FILM_GRAIN = 0x8,
    }
}
