// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_MAP_FLAG // 1
    {
        _DO_NOT_WAIT = 0x100000,
    }
}
