// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_QUERY_MISC_FLAG // 1
    {
        D3D11_QUERY_MISC_PREDICATEHINT = 0x1,
    }
}
