// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_VIDEO_PROCESSOR_NOMINAL_RANGE // 1
    {
        _UNDEFINED = 0x0,
        _16_235 = 0x1,
        _0_255 = 0x2,
    }
}
