// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_RAISE_FLAG // 1
    {
        _DRIVER_INTERNAL_ERROR = 0x1,
    }
}
