// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_VIDEO_PROCESSOR_OUTPUT_RATE // 1
    {
        _NORMAL = 0x0,
        _HALF = 0x1,
        _CUSTOM = 0x2,
    }
}
