// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_BIND_FLAG // 1
    {
        _VERTEX_BUFFER = 0x1,
        _INDEX_BUFFER = 0x2,
        _CONSTANT_BUFFER = 0x4,
        _SHADER_RESOURCE = 0x8,
        _STREAM_OUTPUT = 0x10,
        _RENDER_TARGET = 0x20,
        _DEPTH_STENCIL = 0x40,
        _UNORDERED_ACCESS = 0x80,
        _DECODER = 0x200,
        _VIDEO_ENCODER = 0x400,
    }
}
