// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_FILTER_REDUCTION_TYPE // 1
    {
        _STANDARD = 0x0,
        _COMPARISON = 0x1,
        _MINIMUM = 0x2,
        _MAXIMUM = 0x3,
    }
}
