// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_VDOV_DIMENSION // 1
    {
        _UNKNOWN = 0x0,
        _TEXTURE2D = 0x1,
    }
}
