// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D11_BUFFEREX_SRV_FLAG // 1
    {
        _RAW = 0x1,
    }
}
