// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID3D11Buffer: ID3D11Resource
    {
        static Guid s_uuid = new Guid("48570b85-d1ee-4fcd-a250-eb350722b037");
        public static new ref Guid IID => ref s_uuid;
                
        public virtual void GetDesc(
            out D3D11_BUFFER_DESC pDesc
        ){
            var fp = GetFunctionPointer(10);
            if(m_GetDescFunc==null) m_GetDescFunc = (GetDescFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDescFunc));
            
            m_GetDescFunc(m_ptr, out pDesc);
        }
        delegate void GetDescFunc(IntPtr self, out D3D11_BUFFER_DESC pDesc);
        GetDescFunc m_GetDescFunc;

    }
}
