// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID3D11DomainShader: ID3D11DeviceChild
    {
        static Guid s_uuid = new Guid("f582c508-0f36-490c-9977-31eece268cfa");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
    }
}
