// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    [StructLayout(LayoutKind.Sequential)]
    public struct __MIDL___MIDL_itf_documenttarget_0000_0001_0001 // 1
    {
        public uint JobId;
        public int CurrentDocument;
        public int CurrentPage;
        public int CurrentPageTotal;
        public PrintDocumentPackageCompletion Completion;
        public int PackageStatus;
    }
    // forward declaration PrintDocumentPackageTarget;
    // forward declaration PrintDocumentPackageTargetFactory;
    // forward declaration PrintDocumentPackageTarget;
    // forward declaration PrintDocumentPackageTargetFactory;
}
