// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public static partial class DXGI_ENUM_MODES {
        public const uint _STEREO = ( 4 );
        public const uint _DISABLED_STEREO = ( 8 );
    }
}
