// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_MODE_DESC // 1
    {
        public uint Width;
        public uint Height;
        public DXGI_RATIONAL RefreshRate;
        public DXGI_FORMAT Format;
        public DXGI_MODE_SCANLINE_ORDER ScanlineOrdering;
        public DXGI_MODE_SCALING Scaling;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_GAMMA_CONTROL_CAPABILITIES // 1
    {
        public int ScaleAndOffsetSupported;
        public float MaxConvertedValue;
        public float MinConvertedValue;
        public uint NumGammaControlPoints;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=1025)]public float[] ControlPointPositions;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_GAMMA_CONTROL // 1
    {
        public DXGI_RGB Scale;
        public DXGI_RGB Offset;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=1025)]public DXGI_RGB[] GammaCurve;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_RGB // 1
    {
        public float Red;
        public float Green;
        public float Blue;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct _D3DCOLORVALUE // 1
    {
        public float r;
        public float g;
        public float b;
        public float a;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_JPEG_AC_HUFFMAN_TABLE // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=16)]public byte[] CodeCounts;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=162)]public byte[] CodeValues;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_JPEG_DC_HUFFMAN_TABLE // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=12)]public byte[] CodeCounts;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=12)]public byte[] CodeValues;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_JPEG_QUANTIZATION_TABLE // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=64)]public byte[] Elements;
    }
}
