// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public static partial class Constants {
    }
    public struct IID { public Guid Value; }
    public struct GUID { public _GUID Value; }
    [StructLayout(LayoutKind.Sequential)]
    public struct _GUID
    {
        public uint Data1;
        public ushort Data2;
        public ushort Data3;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=8)]public byte[] Data4;
    }
}
