// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    [StructLayout(LayoutKind.Explicit)]
    public struct mmtime_tag__anonymous_2 // 2
    {
        [FieldOffset(0)]
        public uint ms;
        [FieldOffset(0)]
        public uint sample;
        [FieldOffset(0)]
        public uint cb;
        [FieldOffset(0)]
        public uint ticks;
       // anonymous struct __param__;
       // anonymous struct smpte;
       // anonymous struct __param__;
       // anonymous struct midi;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct mmtime_tag___anonymous_3 // 2
    {
        public byte hour;
        public byte min;
        public byte sec;
        public byte frame;
        public byte fps;
        public byte dummy;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst=2)]public byte[] pad;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct mmtime_tag___anonymous_4 // 2
    {
        public uint songptrpos;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct mmtime_tag // 4
    {
        public uint wType;
        public mmtime_tag__anonymous_2 __param__2;
        public mmtime_tag__anonymous_2 u;
    }
}
