// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public static partial class Constants {
        public const int TIMERR_NOERROR = ( 0 );
        public const int TIMERR_NOCANDO = ( /*TIMERR_BASE*/96 + 1 );
        public const int TIMERR_STRUCT = ( /*TIMERR_BASE*/96 + 33 );
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct TIMECAPS // 4
    {
        public uint wPeriodMin;
        public uint wPeriodMax;
    }
    public static class timeapi {
        [DllImport("winmm.dll")]
        public static extern uint timeGetSystemTime(
            out mmtime_tag pmmt,
            uint cbmmt
        );
        [DllImport("winmm.dll")]
        public static extern uint timeGetTime(
        );
        [DllImport("winmm.dll")]
        public static extern uint timeGetDevCaps(
            out TIMECAPS ptc,
            uint cbtc
        );
        [DllImport("winmm.dll")]
        public static extern uint timeBeginPeriod(
            uint uPeriod
        );
        [DllImport("winmm.dll")]
        public static extern uint timeEndPeriod(
            uint uPeriod
        );
    }
}
