// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum _D3D_SHADER_VARIABLE_CLASS // 1
    {
        _SCALAR = 0x0,
        _VECTOR = 0x1,
        _MATRIX_ROWS = 0x2,
        _MATRIX_COLUMNS = 0x3,
        _OBJECT = 0x4,
        _STRUCT = 0x5,
        _INTERFACE_CLASS = 0x6,
        _INTERFACE_POINTER = 0x7,
        D3D10_SVC_SCALAR = 0x0,
        D3D10_SVC_VECTOR = 0x1,
        D3D10_SVC_MATRIX_ROWS = 0x2,
        D3D10_SVC_MATRIX_COLUMNS = 0x3,
        D3D10_SVC_OBJECT = 0x4,
        D3D10_SVC_STRUCT = 0x5,
        D3D11_SVC_INTERFACE_CLASS = 0x6,
        D3D11_SVC_INTERFACE_POINTER = 0x7,
        _FORCE_DWORD = 0x7fffffff,
    }
}
