// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D_TESSELLATOR_DOMAIN // 1
    {
        _UNDEFINED = 0x0,
        _ISOLINE = 0x1,
        _TRI = 0x2,
        _QUAD = 0x3,
        D3D11_TESSELLATOR_DOMAIN_UNDEFINED = 0x0,
        D3D11_TESSELLATOR_DOMAIN_ISOLINE = 0x1,
        D3D11_TESSELLATOR_DOMAIN_TRI = 0x2,
        D3D11_TESSELLATOR_DOMAIN_QUAD = 0x3,
    }
}
