// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D_REGISTER_COMPONENT_TYPE // 1
    {
        _UNKNOWN = 0x0,
        _UINT32 = 0x1,
        _SINT32 = 0x2,
        _FLOAT32 = 0x3,
        D3D10_REGISTER_COMPONENT_UNKNOWN = 0x0,
        D3D10_REGISTER_COMPONENT_UINT32 = 0x1,
        D3D10_REGISTER_COMPONENT_SINT32 = 0x2,
        D3D10_REGISTER_COMPONENT_FLOAT32 = 0x3,
    }
}
