// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_ALPHA_MODE // 1
    {
        _UNKNOWN = 0x0,
        _PREMULTIPLIED = 0x1,
        _STRAIGHT = 0x2,
        _IGNORE = 0x3,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
