// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_THREADING_MODE // 1
    {
        _SINGLE_THREADED = 0x0,
        _MULTI_THREADED = 0x1,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
