// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_STROKE_TRANSFORM_TYPE // 1
    {
        _NORMAL = 0x0,
        _FIXED = 0x1,
        _HAIRLINE = 0x2,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
