// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_BUFFER_PRECISION // 1
    {
        _UNKNOWN = 0x0,
        _8BPC_UNORM = 0x1,
        _8BPC_UNORM_SRGB = 0x2,
        _16BPC_UNORM = 0x3,
        _16BPC_FLOAT = 0x4,
        _32BPC_FLOAT = 0x5,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
