// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_PRIMITIVE_BLEND // 1
    {
        _SOURCE_OVER = 0x0,
        _COPY = 0x1,
        _MIN = 0x2,
        _ADD = 0x3,
        _MAX = 0x4,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
