// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DXGI_SWAP_CHAIN_COLOR_SPACE_SUPPORT_FLAG // 1
    {
        _PRESENT = 0x1,
        _OVERLAY_PRESENT = 0x2,
    }
}
