// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DISPLAYCONFIG_MODE_INFO_TYPE // 1
    {
        _SOURCE = 0x1,
        _TARGET = 0x2,
        _DESKTOP_IMAGE = 0x3,
        _FORCE_UINT32 = unchecked((int)0xffffffff),
    }
}
