// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY // 1
    {
        _OTHER = unchecked((int)0xffffffff),
        _HD15 = 0x0,
        _SVIDEO = 0x1,
        _COMPOSITE_VIDEO = 0x2,
        _COMPONENT_VIDEO = 0x3,
        _DVI = 0x4,
        _HDMI = 0x5,
        _LVDS = 0x6,
        _D_JPN = 0x8,
        _SDI = 0x9,
        _DISPLAYPORT_EXTERNAL = 0xa,
        _DISPLAYPORT_EMBEDDED = 0xb,
        _UDI_EXTERNAL = 0xc,
        _UDI_EMBEDDED = 0xd,
        _SDTVDONGLE = 0xe,
        _MIRACAST = 0xf,
        _INDIRECT_WIRED = 0x10,
        _INDIRECT_VIRTUAL = 0x11,
        _INTERNAL = unchecked((int)0x80000000),
        _FORCE_UINT32 = unchecked((int)0xffffffff),
    }
}
