// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class IDXGIDevice1: IDXGIDevice
    {
        static Guid s_uuid = new Guid("77db970f-6276-48ba-ba28-070143b4392c");
        public static new ref Guid IID => ref s_uuid;
                
        public virtual int SetMaximumFrameLatency(
            uint MaxLatency
        ){
            var fp = GetFunctionPointer(12);
            if(m_SetMaximumFrameLatencyFunc==null) m_SetMaximumFrameLatencyFunc = (SetMaximumFrameLatencyFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetMaximumFrameLatencyFunc));
            
            return m_SetMaximumFrameLatencyFunc(m_ptr, MaxLatency);
        }
        delegate int SetMaximumFrameLatencyFunc(IntPtr self, uint MaxLatency);
        SetMaximumFrameLatencyFunc m_SetMaximumFrameLatencyFunc;

        public virtual int GetMaximumFrameLatency(
            out uint pMaxLatency
        ){
            var fp = GetFunctionPointer(13);
            if(m_GetMaximumFrameLatencyFunc==null) m_GetMaximumFrameLatencyFunc = (GetMaximumFrameLatencyFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetMaximumFrameLatencyFunc));
            
            return m_GetMaximumFrameLatencyFunc(m_ptr, out pMaxLatency);
        }
        delegate int GetMaximumFrameLatencyFunc(IntPtr self, out uint pMaxLatency);
        GetMaximumFrameLatencyFunc m_GetMaximumFrameLatencyFunc;

    }
}
