// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D3D10_TEXTURE_ADDRESS_MODE // 1
    {
        _WRAP = 0x1,
        _MIRROR = 0x2,
        _CLAMP = 0x3,
        _BORDER = 0x4,
        _MIRROR_ONCE = 0x5,
    }
}
