// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID3D10DepthStencilState: ID3D10DeviceChild
    {
        static Guid s_uuid = new Guid("2b4b1cc8-a4ad-41f8-8322-ca86fc3ec675");
        public static new ref Guid IID => ref s_uuid;
                
        public virtual void GetDesc(
            out D3D10_DEPTH_STENCIL_DESC pDesc
        ){
            var fp = GetFunctionPointer(7);
            if(m_GetDescFunc==null) m_GetDescFunc = (GetDescFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDescFunc));
            
            m_GetDescFunc(m_ptr, out pDesc);
        }
        delegate void GetDescFunc(IntPtr self, out D3D10_DEPTH_STENCIL_DESC pDesc);
        GetDescFunc m_GetDescFunc;

    }
}
