// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum D2D1_FILTER // 1
    {
        _MIN_MAG_MIP_POINT = 0x0,
        _MIN_MAG_POINT_MIP_LINEAR = 0x1,
        _MIN_POINT_MAG_LINEAR_MIP_POINT = 0x4,
        _MIN_POINT_MAG_MIP_LINEAR = 0x5,
        _MIN_LINEAR_MAG_MIP_POINT = 0x10,
        _MIN_LINEAR_MAG_POINT_MIP_LINEAR = 0x11,
        _MIN_MAG_LINEAR_MIP_POINT = 0x14,
        _MIN_MAG_MIP_LINEAR = 0x15,
        _ANISOTROPIC = 0x55,
        _FORCE_DWORD = unchecked((int)0xffffffff),
    }
}
