// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID2D1OffsetTransform: ID2D1TransformNode
    {
        static Guid s_uuid = new Guid("3fe6adea-7643-4f53-bd14-a0ce63f24042");
        public static new ref Guid IID => ref s_uuid;
                
        public virtual void SetOffset(
            tagPOINT offset
        ){
            var fp = GetFunctionPointer(4);
            if(m_SetOffsetFunc==null) m_SetOffsetFunc = (SetOffsetFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetOffsetFunc));
            
            m_SetOffsetFunc(m_ptr, offset);
        }
        delegate void SetOffsetFunc(IntPtr self, tagPOINT offset);
        SetOffsetFunc m_SetOffsetFunc;

        public virtual tagPOINT GetOffset(
        ){
            var fp = GetFunctionPointer(5);
            if(m_GetOffsetFunc==null) m_GetOffsetFunc = (GetOffsetFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetOffsetFunc));
            
            return m_GetOffsetFunc(m_ptr);
        }
        delegate tagPOINT GetOffsetFunc(IntPtr self);
        GetOffsetFunc m_GetOffsetFunc;

    }
}
