// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public class ID2D1ConcreteTransform: ID2D1TransformNode
    {
        static Guid s_uuid = new Guid("1a799d8a-69f7-4e4c-9fed-437ccc6684cc");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int SetOutputBuffer(
            D2D1_BUFFER_PRECISION bufferPrecision,
            D2D1_CHANNEL_DEPTH channelDepth
        ){
            var fp = GetFunctionPointer(4);
            if(m_SetOutputBufferFunc==null) m_SetOutputBufferFunc = (SetOutputBufferFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetOutputBufferFunc));
            
            return m_SetOutputBufferFunc(m_ptr, bufferPrecision, channelDepth);
        }
        delegate int SetOutputBufferFunc(IntPtr self, D2D1_BUFFER_PRECISION bufferPrecision, D2D1_CHANNEL_DEPTH channelDepth);
        SetOutputBufferFunc m_SetOutputBufferFunc;

        public virtual void SetCached(
            int isCached
        ){
            var fp = GetFunctionPointer(5);
            if(m_SetCachedFunc==null) m_SetCachedFunc = (SetCachedFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetCachedFunc));
            
            m_SetCachedFunc(m_ptr, isCached);
        }
        delegate void SetCachedFunc(IntPtr self, int isCached);
        SetCachedFunc m_SetCachedFunc;

    }
}
