// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DIALOG_CONTROL_DPI_CHANGE_BEHAVIORS // 1
    {
        _DEFAULT = 0x0,
        _DISABLE_FONT_UPDATE = 0x1,
        _DISABLE_RELAYOUT = 0x2,
    }
}
