// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public static partial class PM {
        public const uint _NOREMOVE = 0x0000;
        public const uint _REMOVE = 0x0001;
        public const uint _NOYIELD = 0x0002;
        public const uint _QS_INPUT = ( QS._INPUT << 16 );
        public const uint _QS_POSTMESSAGE = ( ( QS._POSTMESSAGE | QS._HOTKEY | QS._TIMER ) << 16 );
        public const uint _QS_PAINT = ( QS._PAINT << 16 );
        public const uint _QS_SENDMESSAGE = ( QS._SENDMESSAGE << 16 );
    }
}
