// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace ShrimpDX {
    public enum DXGI_OUTDUPL_POINTER_SHAPE_TYPE // 1
    {
        _MONOCHROME = 0x1,
        _COLOR = 0x2,
        _MASKED_COLOR = 0x4,
    }
}
